yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('groups/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    posts = Post.objects.order_by('-pub_date')[:10]
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


# def group_list(request):
#     template = 'posts/group_list.html'
#     return render(request, template)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {% load static %}
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="../static/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <title>Последние обновления на сайте</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
<!DOCTYPE html>
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!DOCTYPE html>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        {% load static %}
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:main_page' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
    <title>
        Последние обновления на сайте:
    </title>
{% endblock %}
<body>
    {% block content %}
    <div class="container py-5">
        {% for post in posts %}
            <ul>
                <li>
                    Автор: {{ post.author.get_fullname }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% if post.group %}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
</div>
{% endblock %}
</body>>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
      <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ text }}</h1>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 30 июля 1854
            </li>
          </ul>
          <p>
            [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
            Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо.
            Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться
            къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде
            и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
            ебѣ за нынѣшній день. (3)
          </p>
          <a href="group_list.html">все записи группы</a>
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 29 июля 1854
            </li>
          </ul>
          <p>
            Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки
            съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ,
            что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень
            веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня;
            отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками.
            — Тогда бы я всегда былъ веселъ и почти всегда счастливъ.
            Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ,
            чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ
            накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за
            безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
          </p>
          <a href="group_list.html">все записи группы</a>
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 28 июля 1854
            </li>
          </ul>
          <p>
            Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ.
            Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и
            Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ
            хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и
            Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности,
            днемъ своимъ очень доволенъ. (1)
          </p>
          <a href="group_list.html">все записи группы</a>
        </article>
        <!-- под последним постом нет линии -->
      </div>
    </main>
{% endblock %}